-- CreateTable
CREATE TABLE `contract` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `contract_type` VARCHAR(191) NULL,
    `supplier_name` VARCHAR(191) NULL,
    `supplier_inn` BIGINT UNSIGNED NULL,
    `supplier_kpp` BIGINT UNSIGNED NULL,
    `supplier_ogrn` BIGINT UNSIGNED NULL,
    `supplier_bik` VARCHAR(191) NULL,
    `supplier_corr_account` BIGINT UNSIGNED NULL,
    `supplier_payment_account` BIGINT UNSIGNED NULL,
    `supplier_email` VARCHAR(191) NULL,
    `supplier_phone` VARCHAR(191) NULL,
    `supplier_address` VARCHAR(191) NULL,
    `supplier_bank_name` VARCHAR(191) NULL,
    `customer_name` VARCHAR(191) NULL,
    `customer_inn` BIGINT UNSIGNED NULL,
    `customer_kpp` BIGINT UNSIGNED NULL,
    `customer_ogrn` BIGINT UNSIGNED NULL,
    `customer_bik` VARCHAR(191) NULL,
    `customer_corr_account` BIGINT UNSIGNED NULL,
    `customer_payment_account` BIGINT UNSIGNED NULL,
    `customer_email` VARCHAR(191) NULL,
    `customer_phone` VARCHAR(191) NULL,
    `customer_address` VARCHAR(191) NULL,
    `customer_bank_name` VARCHAR(191) NULL,
    `contract_number` VARCHAR(191) NULL,
    `contract_subject` VARCHAR(191) NULL,
    `item` VARCHAR(191) NULL,
    `contract_sum` BIGINT UNSIGNED NULL,
    `contract_currency` VARCHAR(191) NULL,
    `payment_1_sum` BIGINT UNSIGNED NULL,
    `payment_1_date` VARCHAR(191) NULL,
    `payment_2_sum` BIGINT UNSIGNED NULL,
    `payment_2_date` VARCHAR(191) NULL,
    `contract_date` VARCHAR(191) NULL,
    `contract_start_date` VARCHAR(191) NULL,
    `contract_end_date` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
